
spring:
  datasource:
    username: root
    password: ysjh0014.cn
    url: jdbc:mysql://8.131.78.61:7070/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 8.131.78.61:8848
  application:
    name: gulimall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8000
logging:
  level:
    com.mg.gulimall: debug

