ipAddr: 123.60.98.9
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.131.78.61:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
server:
  port: 12000
logging:
  level:
    com.mg.gulimall: info
