ipAddr: 123.60.98.9
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 8.131.78.61:8848
  redis:
    host: ${ipAddr}
server:
  port: 40000
gulimall:
  thread:
    core-size: 10
    max-size: 100
    keep-alive-time: 5
nacos-dis
