ipAddr: 123.60.98.9
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 8.131.78.61:8848
  redis:
    host: ${ipAddr}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 40000
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
